# Stage 1 - the build process
FROM node:12
WORKDIR /usr/src/app
COPY package*.json ./
ARG PRIVATE_KEY
ARG RECAPTCHA_SECRET
ARG REACT_APP_RECAPTCHA
ARG HYPERION_ENDPOINT
ENV PRIVATE_KEY=$PRIVATE_KEY
ENV RECAPTCHA_SECRET=$RECAPTCHA_SECRET
ENV REACT_APP_RECAPTCHA=$REACT_APP_RECAPTCHA
ENV HYPERION_ENDPOINT=$HYPERION_ENDPOINT

RUN yarn
COPY . ./
RUN yarn build

EXPOSE 8080

CMD ["node", "server.js"]